!*    NAMELIST *BETHY_CTL* To control BETHY module.
!                                                                 
!      
!      NAME     TYPE      PURPOSE                                       
!      ----     ----      -------                                       
!                                                                       
!     *NCANOPY*  INTEGER  Number of canopy layers used

NAMELIST /BETHY_CTL/ &
      NCANOPY
!                                                                       
!     ------------------------------------------------------------------
