MODULE MO_PARRRTM

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!     Parameters relevant to AER's RRTM-LW radiation scheme

!     980714  JJMorcrette
!     ------------------------------------------------------------------

INTEGER, PARAMETER :: JPG    = 16
INTEGER, PARAMETER :: JPBAND = 16
INTEGER, PARAMETER :: JPXSEC = 4
INTEGER, PARAMETER :: JPINPX = 35
INTEGER, PARAMETER :: JPGPT  = 140

INTEGER, PARAMETER :: NG1  = 8
INTEGER, PARAMETER :: NG2  = 14
INTEGER, PARAMETER :: NG3  = 16
INTEGER, PARAMETER :: NG4  = 14
INTEGER, PARAMETER :: NG5  = 16
INTEGER, PARAMETER :: NG6  = 8
INTEGER, PARAMETER :: NG7  = 12
INTEGER, PARAMETER :: NG8  = 8
INTEGER, PARAMETER :: NG9  = 12
INTEGER, PARAMETER :: NG10 = 6
INTEGER, PARAMETER :: NG11 = 8
INTEGER, PARAMETER :: NG12 = 8
INTEGER, PARAMETER :: NG13 = 4
INTEGER, PARAMETER :: NG14 = 2
INTEGER, PARAMETER :: NG15 = 2
INTEGER, PARAMETER :: NG16 = 8

INTEGER, PARAMETER :: NGS1  = 8
INTEGER, PARAMETER :: NGS2  = 22
INTEGER, PARAMETER :: NGS3  = 38
INTEGER, PARAMETER :: NGS4  = 52
INTEGER, PARAMETER :: NGS5  = 68
INTEGER, PARAMETER :: NGS6  = 76
INTEGER, PARAMETER :: NGS7  = 88
INTEGER, PARAMETER :: NGS8  = 96
INTEGER, PARAMETER :: NGS9  = 108
INTEGER, PARAMETER :: NGS10 = 114
INTEGER, PARAMETER :: NGS11 = 122
INTEGER, PARAMETER :: NGS12 = 130
INTEGER, PARAMETER :: NGS13 = 134
INTEGER, PARAMETER :: NGS14 = 136
INTEGER, PARAMETER :: NGS15 = 138

!     ------------------------------------------------------------------
END MODULE MO_PARRRTM
