MODULE MO_SW


USE MO_KIND  , ONLY : DP

IMPLICIT NONE

SAVE

! PARAMETERS:
!
!  nsw      : number of bands of SW scheme
!
!  novlp    : index for cloud overlap assumption in radiation computation
!             1 : maximum-random overlap
!             2 : maximum overlap
!             3 : random overlap
!
!        - C. Cagnazzo, June 2005:
!        - from 4 to 6 bands, following 26Rcycle Morcrette Code

INTEGER, PARAMETER :: NSW=6
INTEGER, PARAMETER :: NOVLP=1


!     ------------------------------------------------------------------
!*    ** *MO_SW* - COEFFICIENTS FOR SHORTWAVE RADIATION TRANSFER
!     ------------------------------------------------------------------

REAL(DP):: APAD(6,3,7)
REAL(DP):: BPAD(6,3,7)
REAL(DP):: RRAY(6,6)
REAL(DP):: RSUN(6)
REAL(DP):: RPDH1
REAL(DP):: RPDU1
REAL(DP):: RPNH
REAL(DP):: RPNU
REAL(DP):: RSWCE(6)
REAL(DP):: RSWCP(6)
REAL(DP):: RTDH2O
REAL(DP):: RTDUMG
REAL(DP):: RTH2O
REAL(DP):: RTUMG
REAL(DP):: D(6,3)
REAL(DP):: REXPO3(6,2,7)
INTEGER :: NEXPO3(6)

REAL(DP):: RYFWCA(6)
REAL(DP):: RYFWCB(6)
REAL(DP):: RYFWCC(6)
REAL(DP):: RYFWCD(6)
REAL(DP):: RYFWCE(6)
REAL(DP):: RYFWCF(6)

REAL(DP):: REBCUA(6)
REAL(DP):: REBCUB(6)
REAL(DP):: REBCUC(6)
REAL(DP):: REBCUD(6)
REAL(DP):: REBCUE(6)
REAL(DP):: REBCUF(6)
REAL(DP):: REBCUG(16)
REAL(DP):: REBCUH(16)
REAL(DP):: REBCUI(6)
REAL(DP):: REBCUJ(6)

REAL(DP):: RASWCA(6)
REAL(DP):: RASWCB(6)
REAL(DP):: RASWCC(6)
REAL(DP):: RASWCD(6)
REAL(DP):: RASWCE(6)
REAL(DP):: RASWCF(6)

REAL(DP):: RFULIO(16,3)
REAL(DP):: RFLAA0(6)
REAL(DP):: RFLAA1(6)
REAL(DP):: RFLBB0(6)
REAL(DP):: RFLBB1(6)
REAL(DP):: RFLBB2(6)
REAL(DP):: RFLBB3(6)
REAL(DP):: RFLCC0(6)
REAL(DP):: RFLCC1(6)
REAL(DP):: RFLCC2(6)
REAL(DP):: RFLCC3(6)
REAL(DP):: RFLDD0(6)
REAL(DP):: RFLDD1(6)
REAL(DP):: RFLDD2(6)
REAL(DP):: RFLDD3(6)

REAL(DP):: RHSAVI(16,3)

REAL(DP):: RSUSHE(6)
REAL(DP):: RSUSHF(6)
REAL(DP):: RSUSHH(6)
REAL(DP):: RSUSHK(6)
REAL(DP):: RSUSHA(6)
REAL(DP):: RSUSHG(6)
REAL(DP):: RSUSHFA(4)
REAL(DP):: RSUSHC
REAL(DP):: RSUSHD

REAL(DP):: REFFIA
REAL(DP):: REFFIB
REAL(DP):: RTIW
REAL(DP):: RRIW
REAL(DP):: RROMA(6)
REAL(DP):: RROMB(6)
REAL(DP):: RRASY(6)

REAL(DP):: RHSRA(6)
REAL(DP):: RHSRB(6)
REAL(DP):: RHSRC(6)
REAL(DP):: RHSRD(6)
REAL(DP):: RHSRE(6)
REAL(DP):: RHSRF(6)
REAL(DP):: RHSRTA
REAL(DP):: RHSRTB

REAL(DP):: RTAUA(6,6)
REAL(DP):: RPIZA(6,6)
REAL(DP):: RCGA(6,6)
REAL(DP):: RAER(6,6)
REAL(DP):: RSNOALB(6)
REAL(DP):: RSNOMEL(6)
REAL(DP):: RWEIGS(6)
REAL(DP):: RWEIGV(6)


!        * E.C.M.W.F. PHYSICS PACKAGE *

!     J.-J. MORCRETTE       E.C.M.W.F.      89/07/14

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : ---------------------------------------------------
!  APAD  :  REAL     PADE APPROXIMANTS NUMERATOR
!  BPAD  :  REAL     PADE APPROXIMANTS DENOMINATOR
!  D     :  REAL     TRANSMISSION LIMIT FOR INFINITE ABSORBER AMOUNT
!  RRAY  :  REAL     RAYLEIGH SCATTERING COEFFICIENTS
!  RSUN  :  REAL     SOLAR FRACTION IN SPECTRAL INTERVALS
!  RPDH1 :  1 + EXPONENT PRESSURE DEPENDENCE H2O
!  RPDU1 :  1 + EXPONENT PRESSURE DEPENDENCE UNIFORMLY MIXED GASES
!  RPNH  :  REFERENCE PRESSURE FACTOR FOR H2O
!  RPNU  :  REFERENCE PRESSURE FACTOR FOR UNIFORMLY MIXED GASES
!  RSWCE :  E-TYPE, H2O CONTINUUM ABSORPTION COEFFICIENT 
!  RSWCP :  P-TYPE, H2O CONTINUUM ABSORPTION COEFFICIENT 
!  RTDH2O:  EXPONENT TEMPERATURE DEPENDENCE H2O
!  RTDUMG:  EXPONENT TEMPERATURE DEPENDENCE UNIFORMLY MIXED GASES
!  RTH2O :  REFERENCE TEMPERATURE H2O
!  RTUMG :  REFERENCE TEMPERATURE UNIFORMLY MIXED GASES
!     -----------------------------------------------------------------

!        * E.C.M.W.F. PHYSICS PACKAGE *

!     J.-J. MORCRETTE       E.C.M.W.F.      89/07/14

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : ---------------------------------------------------
!*    FOUQUART (1987) WATER CLOUD OPTICAL PROPERTIES

! RYFWCA :  REAL   : C1 IN OPTICAL THICKNESS FORMULA
! RYFWCB :  REAL   : C2 IN OPTICAL THICKNESS FORMULA
! RYFWCC :  REAL   : SINGLE SCATTERING ALBEDO PARAMETER
! RYFWCD :  REAL   : SINGLE SCATTERING ALBEDO PARAMETER
! RYFWCE :  REAL   : SINGLE SCATTERING ALBEDO PARAMETER
! RYFWCF :  REAL   : ASSYMETRY FACTOR

!*    SLINGO (1989) WATER CLOUD OPTICAL PROPERTIES

! RASWCA :  REAL   : C1 IN OPTICAL THICKNESS FORMULA
! RASWCB :  REAL   : C2 IN OPTICAL THICKNESS FORMULA
! RASWCC :  REAL   : SINGLE SCATTERING ALBEDO PARAMETER
! RASWCD :  REAL   : SINGLE SCATTERING ALBEDO PARAMETER
! RASWCE :  REAL   : SINGLE SCATTERING ALBEDO PARAMETER
! RASWCF :  REAL   : ASSYMETRY FACTOR

!*   SAVIJARVI (1998) WATER CLOUD OPTICAL PROPERTIES (RRTM)

! RHSAVI : REAL    : MASS ABSORPTION COEFFICIENTS (POLYNOMIAL DEVELOPM)

!*    ICE CLOUD OPTICAL PROPERTIES DERIVED FROM EBERT-CURRY (1992)

! REBCUA :  REAL   : C1 IN OPTICAL THICKNESS FORMULA
! REBCUB :  REAL   : C2 IN OPTICAL THICKNESS FORMULA
! REBCUC :  REAL   : 1-C3  IN SINGLE SCATTERING ALBEDO FORMULA
! REBCUD :  REAL   : C4 IN SINGLE SCATTERING ALBEDO FORMULA
! REBCUE :  REAL   : C5 IN ASSYMETRY FACTOR FORMULA
! REBCUF :  REAL   : C6 IN ASSYMETRY FACTOR FORMULA
! REBCUG :  REAL   : C7 IN MASS ABSORPTION COEFFICIENT FORMULA
! REBCUH :  REAL   : C8 IN MASS ABSORPTION COEFFICIENT FORMULA
! REBCUI :  REAL   : C7 IN MASS ABSORPTION COEFFICIENT SPECTRAL FORMULA
! REBCUJ :  REAL   : C8 IN MASS ABSORPTION COEFFICIENT SPECTRAL FORMULA

!*    ICE CLOUD OPTICAL PROPERTIES DERIVED FROM SUN-SHINE (1995)

! RSHSUE :  REAL   : E IN SINGLE SCATTERING ALBEDO FORMULA
! RSHSUF :  REAL   : F IN SINGLE SCATTERING ALBEDO FORMULA
! RSHSUH :  REAL   : H IN ASSYMETRY FACTOR FORMULA
! RSHSUK :  REAL   : K IN ASSYMETRY FACTOR FORMULA
! RSHSUA :  REAL   : ALPHA IN SSA CORRECTION FACTOR FORMULA
! RSHSUG :  REAL   : GAMMA IN ASSYMETRY CORRECTION FACTOR FORMULA
! RSHSUFA:  REAL   : COEFFICIENTS IN TEMPERATURE CORRECTION FACTOR

! REFFIA :  REAL   : C9  IN EFFECTIVE RADIUS FORMULA
! REFFIB :  REAL   : C10 IN EFFECTIVE RADIUS FORMULA

!*    ICE CLOUD OPTICAL PROPERTIES DERIVED FROM FU-LIOU (1993)

! RFULIO :  REAL   : COEFFICIENTS IN EXPRESSION FOR LW EXTINCTION COEFF.
! RFLAA  :  REAL   : COEFFICIENTS IN EXPRESSION FOR SW EXTINCTION COEFF.
! RFLBB  :  REAL   : COEFFICIENTS IN EXPRESSION FOR SW SINGLE SCATT.ALB.
! RFLCC  :  REAL   : COEFFICIENTS IN EXPRESSION FOR SW ASSYMETRY FACTOR
! RFLDD  :  REAL   : COEFFICIENTS IN EXPRESSION FOR SW ASSYMETRY FACTOR

!*    TRANSITION BETWEEN LIQUID AND SOLID WATER

! RTIW   :  REAL   : TEMPERATURE THRESHOLD
! RRIW   :  REAL   : TRANSITION RANGE

!*    RAIN OPTICAL PROPERTIES FROM SAVIJARVI (1996)

! RROMA  :  REAL   : COEFFICIENTS FOR SINGLE SCATTERING ALBEDO
! RROMB  :  REAL   : COEFFICIENTS FOR SINGLE SCATTERING ALBEDO
! RRASY  :  REAL   : COEFFICIENTS FOR ASSYMETRY FACTOR
! RHSRA  :  REAL   : COEFFICIENTS FOR OPTICAL THICKNESS
! RHSRB  :  REAL   : COEFFICIENTS FOR OPTICAL THICKNESS
! RHSRC  :  REAL   : COEFFICIENTS FOR SINGLE SCATTERING ALBEDO
! RHSRD  :  REAL   : COEFFICIENTS FOR SINGLE SCATTERING ALBEDO
! RHSRE  :  REAL   : COEFFICIENTS FOR ASSYMETRY FACTOR 
! RHSRF  :  REAL   : COEFFICIENTS FOR ASSYMETRY FACTOR
! RHSRTA :  REAL   : COEFFICIENTS FOR OPTICAL THICKNESS
! RHSRTB :  REAL   : COEFFICIENTS FOR OPTICAL THICKNESS
!     -----------------------------------------------------------------

!        * E.C.M.W.F. PHYSICS PACKAGE *

!     J.-J. MORCRETTE       E.C.M.W.F.      89/07/14

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : -------
!  RTAUA :  REAL     S.W. NORMALIZED OPTICAL THICKNESS AT 0.55 MICRON
!  RPIZA :  REAL     S.W. SINGLE SCATTERING ALBEDO
!  RCGA  :  REAL     S.W. ASSYMETRY FACTOR
!  RAER  :  REAL     L.W. ABSORPTION COEFFICIENTS
!     -----------------------------------------------------------------

!        * E.C.M.W.F. PHYSICS PACKAGE *

!     J.-J. MORCRETTE       E.C.M.W.F.      89/07/14

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : -------
! RSNOALB:  REAL     S.W. SPECTRAL ALBEDO (Fresh Snow) after WARREN
! RSNOMEL:  REAL     S.W. SPECTRAL ALBEDO (Aging Snow) after WARREN

! RWEIGS :  REAL     S.W. SPECTR WEIGHT for soil (Briegleb, Ramanathan)
! RWEIGV :  REAL     S.W. SPECTR WEIGHT for vegetation (BR86)
!     -----------------------------------------------------------------
END MODULE MO_SW
