# SConstruct build file for scons
# Version 0.1 (2018.05.17), written by Willi Kappler


import os
import sys

# Add our own command line option for debug builds
AddOption("--debug-build", action="store_true", dest="debug_build")

# Define system environmen with all shell variables.
env = Environment(ENV = os.environ,
    F77PATH = [".", "../oasis3", "../psmile"],
    F90PATH = [".", "../oasis3", "../psmile"],
    F95PATH = [".", "../oasis3", "../psmile"],
    FORTRANPATH = [".", "../oasis3", "../psmile"]
)

# Only change environmemt if we do a real build
if not (GetOption("help") or GetOption("clean")):
    debug_build = GetOption("debug_build")

    # Specify your compiler and flags here:
    #compiler = "ifort"
    compiler = "mpif90"
    #compile_flags = "-fpp -warn all"
    compile_flags = "-cpp -O3"

    c_compiler = "gcc"
    c_flags = "-Wall -Wextra"
    c_debug_flags = "-g3"
    c_optimize_flags = "-O3"

    debug_flags = "-fpp -g -check all -debug all"
    #optimize_flags = "-fast"
    optimize_flags = ""
    link_flags_debug = "-g -check all -debug all"
    #link_flags_release = "-fast"
    link_flags_release = ""

    env.Replace(LINK = compiler)
    env.Replace(F77 = compiler)
    env.Replace(F90 = compiler)
    env.Replace(F95 = compiler)
    env.Replace(FORTRAN = compiler)
    
    env.Append(FORTRANFLAGS = compile_flags)
    env.Append(F77FLAGS = compile_flags)
    env.Append(F90FLAGS = compile_flags)
    env.Append(F95FLAGS = compile_flags)

    # C compiler
    env.Replace(CC = c_compiler)
    env.Append(CCFLAGS = c_flags)
    #env.Append(CPPDEFINES=["mips"])

    if debug_build:
      env.Append(FORTRANFLAGS = debug_flags)
      env.Append(F77FLAGS = debug_flags)
      env.Append(F90FLAGS = debug_flags)
      env.Append(F95FLAGS = debug_flags)
      env.Append(LINKFLAGS = link_flags_debug)
      env.Append(CCFLAGS = c_debug_flags)
    else:
      env.Append(FORTRANFLAGS = optimize_flags)
      env.Append(F77FLAGS = optimize_flags)
      env.Append(F90FLAGS = optimize_flags)
      env.Append(F95FLAGS = optimize_flags)
      env.Append(LINKFLAGS = link_flags_release)
      env.Append(CCFLAGS = c_optimize_flags)


source_files1 = Glob("*.f")
source_files1 = source_files1 + Glob("*.F")
source_files1 = source_files1 + Glob("*.F90")
source_files1 = source_files1 + Glob("*.c")
source_files1 = source_files1 + Glob("../oasis3/*.o")

# Library('foo', ['f1.c', 'f2.c', 'f3.c'])
# Program('prog.c', LIBS=['foo', 'bar'], LIBPATH='.')

#Program('prog.c', LIBS = 'm',
#                  LIBPATH = ['/usr/lib', '/usr/local/lib'])


env.Program(target="clim", source=source_files1)

